# .github/workflows/go.yml
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Test (Linux host)
        run: go test -v ./...

      - name: Build Windows .exe (cross-compile)
        run: |
          mkdir -p dist
          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -v -o dist/app.exe ./app

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-windows-amd64.exe
          path: dist/app.exe
