# .github/workflows/go.yml
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'go.mod'

      - name: Build app (app/main.go)
        run: |
          mkdir -p dist
          go build -v -o dist/app ./app

      - name: Test (all packages)
        run: go test -v ./...

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-linux-amd64
          path: dist/app
